### ISSUE TITLE
The extension for TYPO3 9.x.x will be?

### ISSUE THREAD

**Issue by typo3ua** [cdaecke/md_newsfrontend#1]
When will be the extension for TYPO3 9.x.x ?

**Comment by cdaecke** [comment]
As you can see, this extension is still in development and the current version is considered as an early alpha. Up to now, I didn't test it with TYPO3 9, but it should work.

I will release a first stable version (compatible with TYPO3 8 and 9) of the extension within the next weeks in the TYPO3 TER.

**Comment by typo3ua** [comment]
Thank you for reply.

**Comment by cdaecke** [comment]
Version 1.0.0 is released: https://extensions.typo3.org/extension/md_newsfrontend/

Feedback welcome!
