### ISSUE TITLE
Feature Request: Mail to admin on submit

### ISSUE THREAD

**Issue by ceekay73** [cdaecke/md_newsfrontend#10]
Would it be possible to implement a notification mail to a (typoscript) defined mailadress when FE-user creates or updates an entry?

**Comment by cdaecke** [comment]
I would rather implement a signal slot ([TYPO3 Api Reference](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Hooks/Concept/Index.html#using-signals)), so everyone can do everything according to his needs. What do you think?

**Comment by ceekay73** [comment]
Sounds good - that's a more general approach.

**Comment by cdaecke** [comment]
Ok, I will go for that, but I dont have time to do it before middle of June.

**Comment by cdaecke** [comment]
The following signal slots are added:

- createActionBeforeSave
- createActionAfterPersist
- updateActionBeforeSave
- deleteActionBeforeDelete

I your own extension you catch a signal from the slot in `createAction()` (so just before saving a new record) with the following lines of code:

`ext_localconf.php`

    $signalSlotDispatcher = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class);

    // slot for ext:md_newsfrontend
    $signalSlotDispatcher->connect(
        \Mediadreams\MdNewsfrontend\Controller\NewsController::class,
        'createActionBeforeSave',
        \Vendor\Extension\Slot\YourClass::class,
        'yourMethod'
    );

The method `yourMethod($news, $obj)` receives two parameter:

- object $news The news object
- object $obj The controller object

Add your class `\Vendor\Extension\Slot\YourClass` with the method `yourMethod` and you are ready to go.

Is this (current master) working for your?

**Comment by ceekay73** [comment]
Yes, it's working perfectly. Thanks for implementing this so quickly.

**Comment by cdaecke** [comment]
Version 1.1.0 is released :-)
