### ISSUE TITLE
Feature delete entry does not work

### ISSUE THREAD

**Issue by typo3ua** [cdaecke/md_newsfrontend#11]
I tried to delete record but can not to do it...

I only see opened modal window and when I click on the button "Delete" nothing happens...

**Comment by cdaecke** [comment]
Questions:

- Did you modify the template `News/List.html`?
- Do you have jQuery included in your project?

**Comment by typo3ua** [comment]
Thank you for your reply.

I use for test `https://github.com/benjaminkott/bootstrap_package/` he has jQuery v3.3.1.

I do not modify the template.

All others constants by default but I still see an error `Uncaught ReferenceError: jQuery is not defined` and I do not know why...

![tx_mdnewsfrontend_newsfe_0](https://user-images.githubusercontent.com/638022/58724833-454e8000-83e6-11e9-8081-b61df0638ed4.png)

When I see this step, I see the error

![tx_mdnewsfrontend_newsfe_1](https://user-images.githubusercontent.com/638022/58725615-441e5280-83e8-11e9-9835-fc60d04f8aba.png)

...and this.. I see the error

![tx_mdnewsfrontend_newsfe_3](https://user-images.githubusercontent.com/638022/58726594-d4f62d80-83ea-11e9-98b4-b763e446bbb7.png)


...but when I click on the button "Create new" or the word "Edit" I see the form and I do not see the error... I see only this...

![tx_mdnewsfrontend_newsfe_2](https://user-images.githubusercontent.com/638022/58725809-c3138b00-83e8-11e9-854d-3755218b63dd.png)

As a result, we have this... if we do not have a form on the page then we have the error and if we have a form on the page then we do not have the error.

What is wrong? 

I think that it is the reason why do not works function delete

**Comment by cdaecke** [comment]
EXT:bootstrap_package loads jQuery in the footer of the website. Load jQuery in the head, and it will work.

**Comment by Frenkii** [comment]
Sorry for reopen.
I have the same error here. And YES I modified the News/List.
But what does the plugin need from the original News/list that the deletion button is working?

I additionally have strage behaviour in the modal
![1](https://user-images.githubusercontent.com/20613151/64961922-cbf47380-d896-11e9-9a54-3c7e23462dae.JPG)

The "Löschen" button and the Red line below are both buttons. What the hell is wrong :)

![2](https://user-images.githubusercontent.com/20613151/64961990-e9c1d880-d896-11e9-91f2-167fad6845f4.JPG)

jQuery is loading in the header.

**Comment by cdaecke** [comment]
Since I can't see your "List.html" template, I can only guess, what could possibly go wrong. 
Maybe the following Javascript is missing?

    <script type="text/javascript">
        (function($){
            $(document).ready(function() {
                $('.delete').on('click', function() {
                    $('#delLink').attr('href', $(this).attr('href'));
                });
            });
        })(jQuery);
    </script>

**Comment by Frenkii** [comment]
Worked! added it via TS seperately.
Thank you so much!

Good work

**Comment by medarob** [comment]
I discovered the same problem. I removed jQuery from the '<head>' and now the delete modal doesn't work anymore. Wouldn't it be better to have all the Javascript at the end of the document?
For example, the Bootstrap Package already includes jquery at the end of the document. If I include jquery at the top, I have 2 jquery libraries included.

So, maybe you can include
```
    $('.delete').on('click', function() {
        $('#delLink').attr('href', $(this).attr('href'));
    });
```
directly into the footer? Maybe wrap it into a condition so that it's only included on pages with the "delete" modal? The integrator can specify those page IDs via a constant and the constant is used in the condition.

**Comment by cdaecke** [comment]
@medarob The template is just a proposal on how it could look like and how it could work. If you need some functionality differently, you can always copy the files into your own extension and change them according your needs.
