### ISSUE TITLE
Issues when using together with ns_news_comments

### ISSUE THREAD

**Issue by sztop** [cdaecke/md_newsfrontend#12]
When using your (by the way great!) plugin together with the extension "ns_news_comments", that allows writing comments to news entries in the frontend, it is not possible anymore to create new news-entries in the frontend. The form to create a news entry is shown but nothing happens when clicking Submit. Do you have any idea which functions could interfere between these two extensions? It would be great to be able to use them both to get a comfortable blog system on tx_news basis.
This behaviour occurs in TYPO3 9.5.7
Thanks in advance
Andreas

**Comment by cdaecke** [comment]
Hi Andreas,

I assume, that `ext:md_newsfrontend` is runnung without problems, as soon as you disable `ext:ns_news_comments`. Is that right?

As I don't know the `ext:ns_news_comments` it is hard to tell, what happens. But as you are saying, that nothing happens (no error at all, even no Javascript error?), I guess, that some Javascript of `ext:ns_news_comments` stops submitting the form of `ext:md_newsfrontend`. So could you please check, if there are some unwanted Javascript events on the submit button of the form or on the form itself?

**Comment by medarob** [comment]
We are using both extensions and it works. However, we discovered a bug in ext:ns_news_comments where the sendEmailToAdmin function is not working properly...

**Comment by cdaecke** [comment]
@sztop Could you fix your issue?

**Comment by cdaecke** [comment]
I close this issue for now. If you still have problems, reopen please.
