### ISSUE TITLE
limit filesize of image and file upload

### ISSUE THREAD

**Issue by medarob** [cdaecke/md_newsfrontend#13]
Hi,

one of our editors uploaded a 5MB image and it would be nice if the form would check the filesize before the image/file is uploaded. For example, set the max image filesize and pdf filesize via constants and show an error message in the frontend, when the filesize exceeds the prefered max filesize.

This would be a nice addition to this great plugin. :)

**Comment by cdaecke** [comment]
Thanks for your input. This feature should be easy to add, so I can schedule it with the next release.

**Comment by cdaecke** [comment]
This feature is added in version 1.1.1 of the extension.

As soon as you fill the constants `allowed_falMedia_size` or `allowed_falRelatedFiles_size` the validation will happen.

Make sure to update your template/partials, if you have changed them.

**Comment by medarob** [comment]
Thank you for adding this feature. :)
I tested it in a website with only the Germany language and the error message appears in english.

![grafik](https://user-images.githubusercontent.com/33951787/65123506-b2b50980-d9f3-11e9-8a2b-290353d7d545.png)

What could be wrong here?

**Comment by cdaecke** [comment]
Did you switch the constant "settings.parsleyjsLang" to "de"?

**Comment by medarob** [comment]
No, after setting `plugin.tx_mdnewsfrontend_newsfe.settings.parsleyjsLang = de` it works :)

Thank you!
