### ISSUE TITLE
Error when creating a new entry in the frontend - GeorgRinger\News\Service\Transliterator\Transliterator not found

### ISSUE THREAD

**Issue by medarob** [cdaecke/md_newsfrontend#15]
Hi,

there seems to be an issue with the newest version of EXT:news 7.3.x

As of version 7.3 of EXT:news the Class GeorgRinger\News\Service\Transliterator\Transliterator is not available anymore and therefor there is an error when we want to create a new entry in the frontend. 

![grafik](https://user-images.githubusercontent.com/33951787/64874301-08339400-d64b-11e9-83c4-f3eff2e1b610.png)

TYPO3 version: 9.5.9
News version: 7.3.1
Newsfrontend: 1.1.0

**Comment by Frenkii** [comment]
same error here

**Comment by cdaecke** [comment]
Thanks for reporting!

The used class of ext:news was removed with [this pull request](https://github.com/georgringer/news/pull/1002), so I adapted the code accordingly.

**Comment by cdaecke** [comment]
Version 1.1.1 is released.

**Comment by medarob** [comment]
Thank you :)

I noticed that the slug field in the news is not generated. The field stays empty after the form is submited. This results into a wrong url. It shows the ID and not the text.

now (id of news article = 154):
```
news/article/154
```
correct would be:
```
news/article/test-article
```

Workaround for now: I have to manually update the slug field.
Is it possible to generate the text inside the slug field automatically?

**Comment by cdaecke** [comment]
Have you cleared all TYPO3 caches?

**Comment by medarob** [comment]
Yes, I cleared the caches and submitted a new news via the frontend and the slug field remains empty.
![grafik](https://user-images.githubusercontent.com/33951787/65133719-6376d500-da03-11e9-8a72-fcb439300a38.png)

**Comment by medarob** [comment]
I also noticed the field in the page properties is called "slug" and not "path_segment"
![grafik](https://user-images.githubusercontent.com/33951787/65134145-1b0be700-da04-11e9-9f87-aea6467ed535.png)

**Comment by cdaecke** [comment]
@medarob I am very sorry. Obviously I have testet this with TYPO3 8 only...

The attached commit should fix this now. Could you please double check?

Regarding the slug: The used field in the news extension is called "path_segement".

**Comment by medarob** [comment]
Thanks,
maybe it's a dumb question but can I require the current state of your project with composer?
There is no new release 1.1.2 and I don't want to edit the files manually so maybe it's possible to add the current project files even if there is no new version?

**Comment by medarob** [comment]
I tested it with the master branch and it seems to work :)

**Comment by cdaecke** [comment]
Good to hear!

I will publish a new version of the extension tonight.
