### ISSUE TITLE
generation of slug has '/' which breaks the frontend

### ISSUE THREAD

**Issue by medarob** [cdaecke/md_newsfrontend#16]
Hi,

one of our editors created a new entry with a `/` in the headline. This results in the url/slug with the `/` which breaks the frontend:
![grafik](https://user-images.githubusercontent.com/33951787/65228437-c41d1500-daca-11e9-9d38-12aaf4ba2ba8.png)

When we create a News directly in the backend, this doesn't happen so it seems to be a problem with the regex, which is used for the slug generation?

Maybe it's somehow related to this: https://forge.typo3.org/issues/87656 ?
or this: https://docs.typo3.org/p/georgringer/news/7.3/en-us/Misc/Changelog/7-1-0.html

best regards

**Comment by cdaecke** [comment]
Thanks for pointing that out, very appreciated!

The attached commit should fix this issue. Are you able to test it again?

**Comment by medarob** [comment]
A test entry with `/` in the headline works here :)
