### ISSUE TITLE
Is it possible to change the date?

### ISSUE THREAD

**Issue by bachblick** [cdaecke/md_newsfrontend#17]
It would be perfect, if the fe_user could set the date of the news record. The Time is not necessary, we use the extensions as a calendar. Thank you for your extension.

I tried somethling like this in FormFields.html :
<div class="form-group setdatetime">
        <label for="datetime"><f:translate key="datetime" /></label>
        <f:form.textfield
                property="datetime"
                value="{news.datetime -> f:format.date(format: 'd.m.Y')}"
                id="date"
                class="form-control flatpickr"
                additionalAttributes="{placeholder:'DD.MM.YYYY'}" />
    </div>

**Comment by cdaecke** [comment]
Which field are you trying to use?

The field `datetime` can't be set in the form out of the box, since this field is set in the controller to the creation date of the record. If you want to use this field, you can use the SignalSlot `createActionBeforeSave` ([see documentation](https://github.com/cdaecke/md_newsfrontend#signal-slots)) in order to overwrite the value with something you provide through the form.

**Comment by bachblick** [comment]
Hi Chris

Thank you for the reply.
Unfortunately, this is to complicated for my TYPO3 expertise :-(

Is it a possibility that I pay you for this work and you add it to the extension?

I wrote this in ‘FormFields.html’

  <div class="form-group setdatetime">
        <label for="datetime"><f:translate key="datetime" /></label>
        <f:form.textfield
                property="datetime"
                value="{news.datetime -> f:format.date(format: 'd.m.Y')}"
                id="date"
                class="form-control flatpickr"
                additionalAttributes="{placeholder:'DD.MM.YYYY'}" />
    </div> 


Können wir auf Deutsch kommunizieren?


Freundliche Grüsse
Reto Schäublin


luna MULTIMEDIA
Reto Schäublin

Bützenenweg 66b
CH - 4450 Sissach
+41 79 632 07 22
rs@luna-multimedia.info
www.luna-multimedia.info

**Comment by cdaecke** [comment]
Hey Reto,

please find attached a small extension, which does the job. Just uncompress it and install it in your TYPO3 instance. After clearing the cache, the value from your above posted form field will be considered.

Let me know if this works for you.

Cheers
chris

PS: No need for a payment. Maybe you can contribute in other places to Open Source :-)

**Comment by cdaecke** [comment]
Oops, wrong attachment. Use this one: 
[md_newsfrontend_extended.zip](https://github.com/cdaecke/md_newsfrontend/files/3821804/md_newsfrontend_extended.zip)

**Comment by bachblick** [comment]
Hey Chris

Thank you very much. I can’t save the record because of the error message for the date. See screenshot.
I allready tried to change the dateformat in ModifyNews.php without success.

TYPO3  9.5.11

Best
Reto

**Comment by cdaecke** [comment]
Please post the screenshot or the error message :-)

**Comment by bachblick** [comment]
![date-news](https://user-images.githubusercontent.com/56827793/68475040-4ef6d200-0227-11ea-8dc2-e18e6b1c072c.jpg)
![date-news-2](https://user-images.githubusercontent.com/56827793/68475192-bad93a80-0227-11ea-9716-e5710ac10b2c.jpg)

**Comment by cdaecke** [comment]
Hm, the second message has nothing to do with the small extension I have sent. Does the warning disappear as soon as you disable the extension `md_newsfrontend_extended`?

And the first message: does it disappear as soon as you disable the extension `md_newsfrontend_extended`?

Are you sure, that you have installed [this version](https://github.com/cdaecke/md_newsfrontend/files/3821804/md_newsfrontend_extended.zip) of the extension?

**Comment by bachblick** [comment]
Yep, and to be sure, I installed it again with your last link. The error remains 'The date "..." was not recognized. It works, when I leave the datefield empty.

**Comment by bachblick** [comment]
![extension-installed](https://user-images.githubusercontent.com/56827793/68481548-d3515100-0237-11ea-8584-31ac94f5cbd8.jpg)

Mayby I did something wrong with the installing? I loaded the folder with ftp in > typo3conf > ext and then activated it in the backend.

**Comment by cdaecke** [comment]
No, that sounds all good, nothing else to do.

For further debugging, please replace the file content of  `Classes/Slot/ModifyNews.php` with the following code and paste the result here when you create a new news entry in the frontend.

    <?php
    namespace Mediadreams\MdNewsfrontendExtended\Slot;

    use TYPO3\CMS\Core\Utility\GeneralUtility;

    /**
     *
     * Modify news record
     */
    class ModifyNews
    {
        /**
         * Use form value of field datetime for news record
         *
         * @param object $news The news object
         * @param object $obj The controller object
         * @return void
         */
        public function setDatetime($news, $obj) {
            $data = GeneralUtility::_GP('tx_mdnewsfrontend_newsfe');
            \TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($data['newNews']);
            $datetime = \DateTime::createFromFormat('d.m.Y', $data['newNews']['datetime']);
            \TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($datetime);

            if ($datetime instanceof \DateTime) {
                $news->setDatetime($datetime);
            }

            exit;
        }
    }

**Comment by bachblick** [comment]
Thanks, but still the same error message.
Maybe this can help?
https://github.com/froemken/typo3-extbase-guide/blob/master/Documentation/Fluid/BestPractice/FormsWithDateTimeObjects.rst

![date-news-3](https://user-images.githubusercontent.com/56827793/68484505-a99b2880-023d-11ea-878d-24970898a38f.jpg)

**Comment by cdaecke** [comment]
Whoops, my fault, I am sorry! This can't work, because the validation of the data happens before the signal slot takes effect...

I will update and release a new version of the extension and let you know, as soon as it is done (hopefully this weekend).

**Comment by cdaecke** [comment]
Ok, the current master of the extension `md_newsfrontend` should now realy do the job. You don't need the little extension `md_newsfrontend_extended` anymore.

You are able to configure the format for `datetime` by changing the constant `plugin.tx_mdnewsfrontend_newsfe.settings.formatDatetime`. Default value is `d.m.Y H:i` which translates to `DD.MM.YYYY HH:MM`.

Are you able to test it and verify that it is working for you?

**Comment by bachblick** [comment]
Sorry, but I still have the same error. 'The date "17.11.2019" was not recognized for format "d.m.Y H:i"'
What I did:
Disable the extended extension
Replace all files of the extension md_newsfrontend
Write the Date form-group in 'FormFields.html'
Clear all caches

**Comment by cdaecke** [comment]
Please change the constant „ plugin.tx_mdnewsfrontend_newsfe.settings.formatDatetime“ to „d.m.Y“ and clear the cache.

**Comment by bachblick** [comment]
PERFECT - thank you very much!

**Comment by cdaecke** [comment]
A new version of the extension is published.
