### ISSUE TITLE
Raise dependency of georgringer/news to >= 8

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [cdaecke/md_newsfrontend#19]
Hi there,

any chance to raise the dependency for news to >= 8? Can't update the news extension and even not the typo3 core 9.5.19 as news 8.x is needed to work properly.

Thanks in advance.

**Comment by cdaecke** [comment]
Currently I am working on an update of the extension, which makes it compatible with ext:news >= 8 und TYPO3 10. Hope to release it within the next days.

**Comment by cdaecke** [comment]
Version 2.0.0 is released

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thank you!
