### ISSUE TITLE
Error viewing news created by md_newsfrontend

### ISSUE THREAD

**Issue by AureliusHogan** [cdaecke/md_newsfrontend#20]
Hy!
First of all: **great extension!**

The extension itself is fine. Installation is fine. I'm able to create, edit and delete news with no problems. Controller: **News**, Action: **List** can be done as well. 

But Controller: **News**, Action: **Detail** **fails** when viewing a news, that was created by md_newsfrontend.

**The error message: **
Cannot access protected property TYPO3\CMS\Extbase\Domain\Model\FrontendUser::$usergroup

**My configuration: **
TYPO3 v10.4.12
georgringer/news v8.5.0
md_newsfrontend v2.0.1
md_unreadnews v 3.0.0

**Current solutions: **
If I edit the problematic news in BE and remove the user from tx_md_newsfrontend_feuser, the news is shown without the error message. The error is also gone, when I just disable extension cdaecke/md_newsfrontend.

As you can imagine, both solutions are not acceptable. 😉

Any idea how I could get rid of this problem?

**Comment by cdaecke** [comment]
Thanks for reporting! This seems to be a problem with changes in the TYPO3 core.

Quick test:
TYPO3 10.4.4 works
TYPO3 10.4.12 is not working and throws the error you described.

I will dig into it.

**Comment by cdaecke** [comment]
Ok, the above information is not correct. After clearing the cache I can reproduce the error with TYPO3 10.4.4 as well...

**Comment by cdaecke** [comment]
I found a solution on [Stackoverflow](https://stackoverflow.com/a/65003393/415353) where a similar problem was discussed:
>Problem is that you're using `@TYPO3\CMS\Extbase\Annotation\ORM\Lazy` for a direct relation to a model. The `@TYPO3\CMS\Extbase\Annotation\ORM\Lazy` annotation is helpful for using it for `ObjectStorage`, it's not recommended to use for other models directly.

Answer by [Thomas Löffler](https://stackoverflow.com/users/4432648/thomas-l%c3%b6ffler)

Could you please double check, if the bugfix b0adfcc helps?

**Comment by AureliusHogan** [comment]
Hi @cdaecke 

finaly I could test your hint and was successful:

```
Index: public/typo3conf/ext/md_newsfrontend/Classes/Domain/Model/News.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/public/typo3conf/ext/md_newsfrontend/Classes/Domain/Model/News.php b/public/typo3conf/ext/md_newsfrontend/Classes/Domain/Model/News.php
--- a/public/typo3conf/ext/md_newsfrontend/Classes/Domain/Model/News.php	(date 1610355794560)
+++ b/public/typo3conf/ext/md_newsfrontend/Classes/Domain/Model/News.php	(date 1610355794560)
@@ -21,7 +21,7 @@
      * Uid of feUser
*
      * @var \TYPO3\CMS\Extbase\Domain\Model\FrontendUser
-     * @TYPO3\CMS\Extbase\Annotation\ORM\Lazy
+     * @ TYPO3\CMS\Extbase\Annotation\ORM\Lazy
*/
     protected $txMdNewsfrontendFeuser = null;
```

Thx for your help!!

**Comment by cdaecke** [comment]
Version 2.0.2 is released.

Thanks again for reporting!
