### ISSUE TITLE
Error when deleting an already set archive date

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [cdaecke/md_newsfrontend#24]
Hi there,

I get the following error, when I save a news with an archive date and later on edit the news, empty the archive date and try to save it again. If I create a news without archive date, there's no problem. Only when changing from already saved date to no date.

(1/3) #1470230767 TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException
Column 'archive' cannot be null

in /var/www/intranet-dm/public/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php line 204
            }
            $connection->update($tableName, $fieldValues, ['uid' => $uid], $types);
        } catch (DBALException $e) {
            throw new SqlErrorException($e->getPrevious()->getMessage(), 1470230767, $e);
        }
        if (!$isRelation) {
            $this->clearPageCache($tableName, $uid);

**Comment by cdaecke** [comment]
Thanks for reporting!

Is the attached bugfix working for you?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Yes, it's working. Thank you!

**Comment by cdaecke** [comment]
Version 3.0.2 released.
