### ISSUE TITLE
The action is not allowed by this plugin / module

### ISSUE THREAD

**Issue by onlineware** [cdaecke/md_newsfrontend#25]
I want to use your extension. I have installed and configured the plugin. FE-User Login finished.

Now, if i click to the "create new" i get following error message:
The action "new" (controller "Mediadreams\MdNewsfrontend\Controller\NewsController") is not allowed by this plugin / module

Why is this action not possible? Same in the edit action.

News plugin version: 9.2.0
News frontend plugin version: 3.0.2

Thanks in advance!

**Comment by cdaecke** [comment]
Which TYPO3 version do you use?

**Comment by onlineware** [comment]
Sorry, i forgot. Typo3 version 10.4.19

**Comment by cdaecke** [comment]
I have done a quick check with TYPO3 v10.4.19, ext:news v9.2.0 and ext:md_newsfrontend v.3.0.2 and can't reproduce the described error.

- is you TYPO3 in composer mode?
- do you use custom templates?
- did you upgrade your TYPO3, or are you testing in a clean new system?
- did you clear the TYPO3 cache also in the install tool?
- is your database up to date? Check in install tool (Analyze database).

**Comment by onlineware** [comment]
Sorry for the late reply.

- no composer mode
- yes i use a custom provider extension and i have extended the news plugin, but also when i deactivate my extended version of news, same problem
- the typo3 system is a new clear version, no upgrade
- yes i cleared the cache also in the install tool
- yes analyse database is ok

I don't know what's going wrong.

**Comment by cdaecke** [comment]
Could you please try to delete the content element with the plugin `News frontend` in the backend and create a new element containing the plugin?

**Comment by onlineware** [comment]
oh, now it works. Thank you very much. How can this be explained?

**Comment by cdaecke** [comment]
Good to hear, that it works now!

Sometimes TYPO3 saves flexform data in the database, which won't be updated later on. So if you remove the content element and add a new one with the plugin, you will get an empty or correctly configured flexform in the database.
