### ISSUE TITLE
Compatibility with EXT:news>= 11 and TYPO3 v12

### ISSUE THREAD

**Issue by iwillenbrock** [cdaecke/md_newsfrontend#27]
Hi, do you plan to raise the dependencies/compatibility to TYPO3 v12 and EXT:news>= 11?
If so, can you foresee when that might happen?

**Comment by cdaecke** [comment]
Yes, this extension will be available for the latest version of `ext:news` and TYPO3 v12. Hopefully I will find some time within the next weeks.

**Comment by cdaecke** [comment]
@iwillenbrock I have just added commit with compatibility to `ext:news` v11 and TYPO3 v12. Are you able to test the current master?

**Comment by iwillenbrock** [comment]
Seems to be working fine in TYPO3 v12. I've got some trouble with images/rights in general with that instance of TYPO3, but everything else seems to be fine.

**Comment by abvdveen** [comment]
Are you releasing this as 3.0.4? Install via composer now still gives 'mediadreams/md_newsfrontend[3.0.0, ..., 3.0.3] require typo3/cms-core ^10.4 || ^11.5'

**Comment by cdaecke** [comment]
New version of extension is released.
