### ISSUE TITLE
I do not see the plugin-tab

### ISSUE THREAD

**Issue by typo3ua** [cdaecke/md_newsfrontend#3]
Hello!

I do not see the plugin-tab, she is missing

![news_frontend](https://user-images.githubusercontent.com/638022/56240228-a0791d00-609b-11e9-8e20-39302de6dd20.png)

CMS TYPO3 9.5.5
ext: news 7.2.0
ext: md_newsfrontend - last
PHP 7.2

**Comment by cdaecke** [comment]
Which plugin tab is missing? Do you mean the the field "Record Storage Page"?

It should look like this:

![newsfrontend_plugin](https://user-images.githubusercontent.com/2102444/56241347-ecc15e80-6095-11e9-8ae2-776e98f27ad1.png)

**Comment by typo3ua** [comment]
Yes I mean "Record Storage Page" I do not see him

**Comment by cdaecke** [comment]
Hm, my sytem is running alomost with the same componets, only difference: I have currently TYPO3 9.5.4. So I think, that a configuration or another extension in your system removes this field in general. Is this possible?

**Comment by typo3ua** [comment]
:) I can add access for test in private .. I doing it here https://dev9.typo3.org.ua
I already did reinstall, cleared flush cache but nothing...
I tested this on the FIreFox and Chrome

I done..
- Install the extension by using the extension manager
- Include the static TypoScript of the extension
- Configure the extension by setting your own constants - I leave by default

**Comment by cdaecke** [comment]
How do you get the marked information? I dont see that in my system?

![md_newsfrontend_plugin](https://user-images.githubusercontent.com/2102444/56244787-0ebedf00-609e-11e9-9be2-94d512f1cb95.png)

**Comment by typo3ua** [comment]
..never mind it is just config / setup TYPO3 for `Application Context Development`

**Comment by cdaecke** [comment]
... and this config does not remove the field by any chance?

**Comment by typo3ua** [comment]
NO Never was this .. it is just showing technical information about field

**Comment by cdaecke** [comment]
Please try to install the extension in a fresh TYPO3 without changing any configuration.

**Comment by typo3ua** [comment]
I did it ...
![news_frontend_0](https://user-images.githubusercontent.com/638022/56246004-7dee0080-60a9-11e9-8549-b580791ab607.png)
====
![typo3_info](https://user-images.githubusercontent.com/638022/56246196-f9e84880-60a9-11e9-8231-8f2d35b9844f.png)

**Comment by typo3ua** [comment]
I think you are need try to install TYPO3 9.5.5...

**Comment by cdaecke** [comment]
I have tested now with TYPO3 9.5.5 and can see the field "Record Storage Page" without any problems.

Can you see the field if you follow theses steps?

- create a new content element of type "General Plugin"
- switch to tab "Plugin"

Now you should see already the field "Record Storage Page". Is this true?

And if you now select in field "Selected Plugin" the "News frontend" it disappears?

**Comment by typo3ua** [comment]
Yes I did as you are written but I do not see this field "Record Storage Page"

![news_frontend_1](https://user-images.githubusercontent.com/638022/56307768-500ec780-614e-11e9-9a2d-2daaa93086ee.png)

...and even when I select the field "Selected Plugin" the "News frontend" this this field "Record Storage Page" not showing

![news_frontend](https://user-images.githubusercontent.com/638022/56307922-a67c0600-614e-11e9-9deb-b43353960754.png)

**Comment by cdaecke** [comment]
As you can see, the field "Record Storage Page" is missing **before** you select the plugin. So I am pretty sure, that it has nothing to do with the extension md_newsfrontend.

But be be absolutely sure, please deactivate the extension md_newsfrontend and do the following steps again afterwards:

- create a new content element of type "General Plugin"
- switch to tab "Plugin"

Is the field "Record Storage Page" no available?

**Comment by typo3ua** [comment]
Yes, you are right.
Now I am looking for a reason and who does it.

**Comment by typo3ua** [comment]
I found it
The reason was this line in my code...
`$GLOBALS['TCA']['tt_content']['columns']['pages']['displayCond'] = 'FIELD:bodytext:=:userpanel';`
I fixed it.
Thanks!
