### ISSUE TITLE
Error when I update (edit) Post

### ISSUE THREAD

**Issue by juri911** [cdaecke/md_newsfrontend#30]
After I click on save, I get the message "Oops, an error occurred! Code: 20240103015256bed48480".
Otherwise I can create and delete posts.

**Comment by cdaecke** [comment]
Please provide more information:

- Version of TYPO3
- Version of extension
- What exactly is the error `20240103015256bed48480`. You can find this information in `var/log/typo3_...log`

**Comment by juri911** [comment]
Hello.
Typo3:  `11.5.32`
News frontend | md_newsfrontend: `3.0.3`

This is the current error message
![Typo3-error-log](https://github.com/cdaecke/md_newsfrontend/assets/8495928/9e6a294a-674b-4321-8cfc-ad497baa8041)

I can create and delete posts (different users) without any problems.

Thanks for the help

**Comment by cdaecke** [comment]
This problem was solved with the current master already.

Please check, if the current master is working for you.

**Comment by juri911** [comment]
Thanks for the reply.
I have installed the current master.
Now this error message comes up
![Typo3-error-log2](https://github.com/cdaecke/md_newsfrontend/assets/8495928/13032328-f5f3-42eb-98c0-69559eda92d8)

Could this be due to the News system Extension `(news) 11.3.0`?

**Comment by cdaecke** [comment]
@juri911 Thanks for the debug output. I have just added a small fix for that.
Can you test with the current master again?

I assume, that you are running your system on PHP 8? As I have not tested this extension with TYPO3 v11 and PHP >7.4, there could be more errors coming up...

**Comment by juri911** [comment]
Hello @cdaecke . Many thanks for your help. Everything works great.
