### ISSUE TITLE
categories not set on create/update

### ISSUE THREAD

**Issue by ps-devstudio** [cdaecke/md_newsfrontend#31]
When I try to create or update a news item, the subcategories set with settings.parentCategory are not written to the database. Of course, I could use $this->eventDispatcher->dispatch(new UpdateActionBeforeSaveEvent($news, $this)); to enable this, but four lines of code in the NewsController.php also do the job.

in public function createAction(News $newNews): ResponseInterface

```
// PSR-14 Event
$this->eventDispatcher->dispatch(new CreateActionBeforeSaveEvent($newNews, $this));
$categories = $arguments['categories'];
$newNews->setCategories($categories);
$this->newsRepository->add($newNews);

```
```
public function updateAction(News $news): ResponseInterface
// PSR-14 Event
$this->eventDispatcher->dispatch(new UpdateActionBeforeSaveEvent($news, $this));
$categories = $requestArguments['news']['categories'];
$news->setCategories($categories);
$this->newsRepository->update($news);
$this->clearNewsCache($news->getUid(), $news->getPid());
```
        
  https://github.com/cdaecke/md_newsfrontend/blob/bd9f18165ea7593dcf5f1188fbce999ced046651/Classes/Controller/NewsController.php#L232
  
 But of course this only sets the categories in tx_news_domain_model_news. It doesn't help to correct set the category.

**Comment by cdaecke** [comment]
Maybe this is a misunderstanding, of what the constant `plugin.tx_mdnewsfrontend_newsfe.settings.parentCategory` is supposed for.

With configuring the constant `plugin.tx_mdnewsfrontend_newsfe.settings.parentCategory`, you define one parent category of which all children shall be shown in the "new" or "edit" template:
https://github.com/cdaecke/md_newsfrontend/blob/bd9f18165ea7593dcf5f1188fbce999ced046651/Resources/Private/Partials/News/FormFields.html#L112-L124

For example your category tree looks something like that:

    - Main 1 (uid=1)
        - Sub 1 (uid=3)
        - Sub 2 (uid=4)
        - Sub 3 (uid=5)
    - Main 2  (uid=2)

Now you set the constant `plugin.tx_mdnewsfrontend_newsfe.settings.parentCategory = 1`. In the form for a new News record (or the editing form) the categories "Sub 1", "Sub 2" and "Sub 3" will be shown, and you are able to select one or more and they will be saved.

Does this answer your issue?

**Comment by ps-devstudio** [comment]
Thank you very much. There is no misunderstanding. In my TYPO3 11.5 installation, I can select the child categories without any problems in the frontend, but they are not being stored in the database. Everything else works fine, and the debug console shows that $_POST contains the correct categories.

**Comment by cdaecke** [comment]
Which version of the extension are you using?

**Comment by cdaecke** [comment]
I have double checked `ext:md_newsfrontend` v4.0.0 with TYPO3 v11 and v12. In my case the categories are saved without any problems.

**Comment by cdaecke** [comment]
Closing, because of lacking feedback.
