### ISSUE TITLE
Image in lists: showinpreview = 1

### ISSUE THREAD

**Issue by philipp-leichtweis** [cdaecke/md_newsfrontend#8]
Hi,

i really like your plugin, but i miss on feature.
"showinpreview" should be by default "1" or be configurable or should be set by the frontend user.

In $queryBuilder in FileUpload.php i added "'showinpreview'     => 1", but thats not the way i should be.
Is there a better way at the moment?

Phil

**Comment by cdaecke** [comment]
I have just added the "showinpreview" select box.

Are you able to double check? If this works for you, I would release a new version of the extension.

**Comment by philipp-leichtweis** [comment]
> I have just added the "showinpreview" select box.
> 
> Are you able to double check? If this works for you, I would release a new version of the extension.

Hi Chris,

thank you very much for this fast answer and implementation. :)

I found two little bugs.

1) If i edit an existing news item which had initial the value="1" in the showinpreview select, it falls back to the value="0". So it doesn't have the latest state and on saving again it will hide the image.

2) Delete a news item throws an exception after submit the deletion, but the news item is deleted:
(1/1) #1297933823 TYPO3\CMS\Extbase\Property\Exception\TargetNotFoundException
Object of type Mediadreams\MdNewsfrontend\Domain\Model\News with identity "471" not found.

Here ist the action-url: .../eintrag-erstellen?tx_mdnewsfrontend_newsfe%5Baction%5D=delete&tx_mdnewsfrontend_newsfe%5Bcontroller%5D=News&tx_mdnewsfrontend_newsfe%5Bnews%5D=471&cHash=353e47c782b555ac85211fdda5f7437b
I think there should be a modal window with the success message of the deletion. I had it one time (can't figure out why, maybe JS-trouble with fancybox) and the whole edit area with class="tx-md-newsfrontend" was rendered in the modal again.

Phil

**Comment by cdaecke** [comment]
>     1. If i edit an existing news item which had initial the value="1" in the showinpreview select, it falls back to the value="0". So it doesn't have the latest state and on saving again it will hide the image.

Are you using the new template (`Partials/News/FormFields.html`), which I have modified yesterday?

If you are using your own template and you do not want to let the users change the value for `showinpreview`, please add a hidden field with the name `falMedia[showinpreview]` and set the value, which you need (0,1 or 2).

>     2. Delete a news item throws an exception after submit the deletion, but the news item is deleted:
>        (1/1) #1297933823 TYPO3\CMS\Extbase\Property\Exception\TargetNotFoundException
>        Object of type Mediadreams\MdNewsfrontend\Domain\Model\News with identity "471" not found.

I can't reproduce this.

> I think there should be a modal window with the success message of the deletion. I had it one time (can't figure out why, maybe JS-trouble with fancybox) and the whole edit area with class="tx-md-newsfrontend" was rendered in the modal again.

The modal window appears on click to the `delete` link. In the modal you have to confirm, that you realy want to delete the entry. This works only, if you have the Twitter Bootstrap Js included.

**Comment by philipp-leichtweis** [comment]
Thanks a lot for your feedback! 

Yes, i use (Partials/News/FormFields.html), you added yesterday. 
I will set a fix value for the preview, it fits my purpose.

I don't use Twitter Bootstrap Js yet. I'll give a try.

**Comment by cdaecke** [comment]
So this issues is solved?

**Comment by philipp-leichtweis** [comment]
Hi Chris, 
sorry, i couldn't test it earlier. Yes, all issues are solved. It works great with the latest boostrap JS.
I think you can release a new version of the extension. :)

**Comment by cdaecke** [comment]
Thanks for your feedback. Version 1.0.1 was just released.
