### ISSUE TITLE
Support of eventnews

### ISSUE THREAD

**Issue by McKoy61** [cdaecke/md_newsfrontend#9]
Is there a possibility to add support for https://github.com/georgringer/eventnews? It extends the news system with a simple event management tool an needs some more fields in case the condition is_event is true.

**Comment by typo3ua** [comment]
Other fields can be added or removed by overwriting the partial 'News/FormFields.html'.

**Comment by cdaecke** [comment]
In addition to the comment of @typo3ua:

You can add more fields in `Partials/News/FormFields.html`. But bare in mind, that you can add only fields, which belong to new `News` model (table `tx_news_domain_model_news`).

For example you could add the flag `is event` with the following code:

    <f:form.checkbox property="isEvent" value="1" id="isEvent" />
